=== lyl123321/xmlSearcher2/data/book/book.dtd
<!ELEMENT book (page*)>
<!ELEMENT page (ID,title,a,s)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT a (p)>
<!ELEMENT s (h,p)>

<!ELEMENT h (t)>
<!ELEMENT p (t)>
<!ELEMENT t (#PCDATA)>

=== lyl123321/xmlSearcher2/data/book/dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "data/book/book.dtd">
<book>
<page>
<ID></ID>
<title></title>
<a>
<p>
<t></t>
</p>
</a>
<s>
<h>
<t></t>
</h>
<p>
<t></t>
</p>
</s>
</page>
</book>
